#! /bin/sh
# /etc/init.d/labbrokerRPi 

### BEGIN INIT INFO
# Provides:          labbrokerRPi
# Required-Start:    $time $network
# Required-Stop:     $time $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts up all the bits for labbrokerRPi
# Description:       Starts up all the bits for labbrokerRPi
### END INIT INFO

# If you want a command to always run, put it here
labbrokerRPi_PATH="__DIR__"

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting labbrokerRPi"
    # run application you want to start
    	php $labbrokerRPi_PATH/startUp.php
    ;;
  stop)
    echo "Stopping labbrokerRPi"
    # kill application you want to stop
    
    ;;
  *)
    echo "Usage: /etc/init.d/labbrokerRPi {start|stop}"
    exit 1
    ;;
esac

exit 0